redis = (loadfile "redis.lua")()
io.write("Enter or Set Bot ID:-")
local last = io.read()
io.popen('rm -rf ~/.telegram-cli/CONTROL-'..last..' CONTROL-'..last..'.lua CONTROL-'..last..'.sh CONTROL_'..last..'_logs.txt')
redis:del('CONTROL:'..last..':*')
print("Done!\nAll Data/Files Of gold Deleted\nCONTROL ID : "..last)
