redis = (loadfile "redis.lua")()
io.write("Enter or set bot ID : ")
local last = io.read()
io.write("\nEnter or set Sudo ID : ")
local sudo=io.read()
local text,ok = io.open("base.lua",'r'):read('*a'):gsub("gold%-ID",last)
io.open("gold-"..last..".lua",'w'):write(text):close()
io.open("gold-"..last..".sh",'w'):write("while true; do\n./telegram-cli-1222 -p gold-"..last.." -s gold-"..last..".lua\ndone"):close()
io.popen("chmod 777 gold-"..last..".sh")
redis:set('gold:'..last..':fullsudo',sudo)
print("Done!\nNew bot Created...\nID : "..last.."\nFull Sudo : "..sudo.."\nRun : ./gold-"..last..".sh")
