redis = (loadfile "redis.lua")()
io.write("Now Enter or set telegram bot ID : ")
local last = io.read()
io.write("\nNow Enter or set Sudo or Admin ID : ")
local sudo=io.read()
local text,ok = io.open("base.lua",'r'):read('*a'):gsub("CONTROL%-ID",last)
io.open("CONTROL-"..last..".lua",'w'):write(text):close()
io.open("CONTROL-"..last..".sh",'w'):write("while true; do\n./telegram-cli-1222 -p CONTROL-"..last.." -s CONTROL-"..last..".lua\ndone"):close()
io.popen("chmod 777 CONTROL-"..last..".sh")
redis:set('CONTROL:'..last..':fullsudo',sudo)
print("Done!\nNew CONTROL Created...\nID : "..last.."\nFull Sudo : "..sudo.."\nRun : ./CONTROL-"..last..".sh")
